"""Shared primitives for every contract in this package.

Three things live here that the rest of the package depends on:

1. `ContractModel` — the base class that makes every contract strict at the boundary.
2. Identifier and scalar types, so an evidence id cannot be passed where a finding id belongs.
3. `DecisionSupportText` — the deterministic language guard that enforces the decision-support
   boundary in `CLAUDE.md`. It is ordinary code, not a prompt instruction, because a model must
   not be the thing that decides whether its own output stayed inside the boundary.
"""

from __future__ import annotations

import re
from datetime import datetime
from enum import StrEnum
from typing import Annotated, Literal, get_args

from pydantic import AfterValidator, BaseModel, ConfigDict, Field, StringConstraints

# ---------------------------------------------------------------------------
# Contract versioning
# ---------------------------------------------------------------------------

ContractVersion = Literal["2.0.0"]
"""The contract set's version, as a type.

Every contract declares `schema_version: ContractVersion`, so a payload written against an
unknown version fails validation loudly instead of being partially understood. Blueprint §10.1:
breaking changes require a new major version and a compatibility plan.

Spelled as a `Literal` of a string constant rather than `Literal[CONTRACT_VERSION]` because the
latter is not a valid type to a type checker — `Literal` needs a literal. `CONTRACT_VERSION`
below is the runtime value, and `_assert_version_agreement` keeps the two from drifting.
"""

CONTRACT_VERSION: ContractVersion = "2.0.0"
"""Runtime value of `ContractVersion`, for use as a field default and in generated schemas."""


def _assert_version_agreement() -> None:
    """Fail at import if the type and the value disagree.

    Bumping one and forgetting the other would produce contracts that validate against a version
    they do not declare — precisely the silent mismatch the version pin exists to prevent.
    """
    permitted = get_args(ContractVersion)
    if CONTRACT_VERSION not in permitted:
        raise RuntimeError(
            f"CONTRACT_VERSION {CONTRACT_VERSION!r} is not a member of ContractVersion {permitted}"
        )


_assert_version_agreement()


# ---------------------------------------------------------------------------
# Base model
# ---------------------------------------------------------------------------


class ContractModel(BaseModel):
    """Base for every contract.

    `extra="forbid"` is the load-bearing setting. These models sit at boundaries between
    ingestion, orchestration, human review, and ASAP delivery, and a silently-dropped unknown
    field at a boundary is how a contract mismatch becomes a data-loss bug. Forbidding extras
    turns that into a validation error at the seam where it happened.

    `frozen=True` supports ADR-011: the machine proposal must remain immutable once a human
    disposition references it. Constructing a variant is `model_copy(update=...)`, which is
    explicit and reviewable, rather than in-place mutation.
    """

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        str_strip_whitespace=True,
        validate_default=True,
        use_enum_values=False,
    )


# ---------------------------------------------------------------------------
# Scalars and identifiers
# ---------------------------------------------------------------------------

NonEmptyStr = Annotated[str, StringConstraints(min_length=1, strip_whitespace=True)]

Sha256 = Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]
"""Lowercase hex SHA-256. Used for policy-pack integrity and delivery payload integrity."""

UtcDatetime = Annotated[datetime, Field(description="Timezone-aware UTC timestamp")]

SemVer = Annotated[str, StringConstraints(pattern=r"^\d+\.\d+\.\d+$")]


# Prefixed, opaque identifiers.
#
# Prefixes are not decoration. `run_id` and `finding_id` are passed adjacently through
# orchestration, delivery, and audit records, and a transposition between them is invisible at a
# type level if both are bare strings. The prefix makes that mistake a validation error.
#
# Written out one per line rather than generated by a helper: a factory returning `Annotated[...]`
# is a *value* to a type checker, not a type alias, so every field annotated with one silently
# degrades to `Any` under mypy. Verbosity here buys real static checking.

_ID_SUFFIX = r"[A-Za-z0-9][A-Za-z0-9_\-]{0,62}$"

CaseId = Annotated[str, StringConstraints(pattern=r"^[A-Z][A-Z0-9\-]{2,63}$")]
"""Case identifiers come from the program, not from us, so this is deliberately permissive."""

SubjectId = Annotated[str, StringConstraints(pattern=r"^[A-Z][A-Z0-9\-]{2,63}$")]
IngestionId = Annotated[str, StringConstraints(pattern=r"^ing_" + _ID_SUFFIX)]
RunId = Annotated[str, StringConstraints(pattern=r"^run_" + _ID_SUFFIX)]
DocumentId = Annotated[str, StringConstraints(pattern=r"^doc_" + _ID_SUFFIX)]
EvidenceId = Annotated[str, StringConstraints(pattern=r"^ev_" + _ID_SUFFIX)]
FindingId = Annotated[str, StringConstraints(pattern=r"^fnd_" + _ID_SUFFIX)]
DispositionId = Annotated[str, StringConstraints(pattern=r"^dsp_" + _ID_SUFFIX)]
MessageId = Annotated[str, StringConstraints(pattern=r"^msg_" + _ID_SUFFIX)]
ReceiptId = Annotated[str, StringConstraints(pattern=r"^rcpt_" + _ID_SUFFIX)]
GapId = Annotated[str, StringConstraints(pattern=r"^gap_" + _ID_SUFFIX)]
PolicyCitationId = Annotated[str, StringConstraints(pattern=r"^pol_" + _ID_SUFFIX)]
ChunkId = Annotated[str, StringConstraints(pattern=r"^chk_" + _ID_SUFFIX)]

PolicyPackId = Annotated[str, StringConstraints(pattern=r"^[a-z0-9][a-z0-9\-]{2,63}$")]
ActorId = Annotated[str, StringConstraints(pattern=r"^[a-z0-9][a-z0-9\-]{2,63}$")]


# ---------------------------------------------------------------------------
# Model tiers (ADR-008)
# ---------------------------------------------------------------------------


class ModelAlias(StrEnum):
    """The only model references application code and contracts may carry.

    ADR-008: concrete Bedrock model IDs, inference-profile IDs, and regions live in LiteLLM
    config. A partition change must be a config change, so a model ID must never reach a
    contract. Blueprint §10.3's example run manifest names a concrete model
    (`case-analysis-sonnet`); that is a divergence this enum deliberately closes.
    """

    ORCHESTRATOR = "ireports-orchestrator"
    THINKING = "ireports-thinking"
    FAST = "ireports-fast"


class DataClassification(StrEnum):
    """`CLAUDE.md`: synthetic data only, in this repo, always.

    The enum has one member on purpose. Production classifications are a program concern and
    adding them here would make it possible for a real-data payload to validate against a
    contract in this repository.
    """

    SYNTHETIC_NO_PII = "SYNTHETIC-NO-PII"


# ---------------------------------------------------------------------------
# Decision-support boundary (CLAUDE.md, blueprint §10.4)
# ---------------------------------------------------------------------------

_DETERMINATIVE_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (
        re.compile(r"\b(is|are|was|were)\s+(not\s+)?(suitable|unsuitable|fit|unfit)\b", re.I),
        "states a suitability or fitness determination",
    ),
    (
        re.compile(r"\b(is|are)\s+(not\s+)?(eligible|ineligible)\b", re.I),
        "states an eligibility determination",
    ),
    (
        # Verb forms: "should be denied", "recommend that eligibility be revoked".
        # The bridge stops at clause boundaries so that an unrelated later clause
        # ("...should be reviewed; access was granted in 2019") is not swept in.
        re.compile(
            r"\b(should|must|shall|recommend(?:s|ed)?)\b[^.;]{0,30}?\b"
            r"(denied|revoked|granted|suspended|debarred|disqualif\w*)\b",
            re.I,
        ),
        "recommends a final adjudicative action",
    ),
    (
        # Noun forms: "recommend denial", "advises revocation of the clearance".
        re.compile(
            r"\b(recommend(?:s|ed|ation|ations)?|advise[sd]?|propose[sd]?)\b[^.;]{0,30}?\b"
            r"(denial|revocation|suspension|debarment|disqualification)\b",
            re.I,
        ),
        "recommends a final adjudicative action",
    ),
    (
        re.compile(
            r"\bclearance\s+(should|must|shall|will)\s+be\b|\b(deny|revoke|grant|suspend)\s+"
            r"(the\s+)?(clearance|eligibility|access)\b",
            re.I,
        ),
        "directs a clearance action",
    ),
    (
        re.compile(r"\bviolated\s+(SEAD|5\s*CFR|the\s+(guideline|standard|policy))", re.I),
        "asserts a legal violation as fact",
    ),
    (
        re.compile(
            r"\b(subject|applicant|individual)\s+(is|was)\s+(deceptive|dishonest|lying)\b", re.I
        ),
        "asserts a credibility conclusion reserved to the officer",
    ),
    (
        re.compile(
            r"\b(will|is\s+likely\s+to)\s+(reoffend|commit|engage\s+in\s+misconduct)\b", re.I
        ),
        "predicts future misconduct",
    ),
)


def reject_determinative_language(value: str) -> str:
    """Reject narrative text that crosses the decision-support boundary.

    The system identifies evidence-backed issues for review by an authorized officer. It must
    never grant, deny, revoke, suspend, or otherwise make a final determination. That boundary
    is enforced here, deterministically, on every narrative field a model can write into.

    This is a guard, not a proof. It catches the specific formulations blueprint §10.4 lists as
    prohibited, and it cannot catch every possible phrasing.

    **It used to have a backstop and no longer does.** An earlier version of this docstring called
    it "not a substitute for the human review gate (ADR-011)" — but ADR-022 removed that gate
    entirely, because review happens in ASAP rather than inside a run. The boundary now rests on
    two mechanisms, not three: this guard, and the fact that `ProposedFinding` is the only finding
    type there is. Weakening either one is not a defence-in-depth trade; it is the boundary.
    """
    for pattern, why in _DETERMINATIVE_PATTERNS:
        match = pattern.search(value)
        if match:
            raise ValueError(
                f"text crosses the decision-support boundary: it {why} "
                f"(matched {match.group(0)!r}). Findings describe what the record indicates and "
                f"what requires officer review; they do not state determinations."
            )
    return value


DecisionSupportText = Annotated[
    str,
    StringConstraints(min_length=1, strip_whitespace=True),
    AfterValidator(reject_determinative_language),
]
"""Narrative text a model may write. Guarded against determinative language."""


# ---------------------------------------------------------------------------
# Shared enums
# ---------------------------------------------------------------------------


class DecisionDomain(StrEnum):
    """The distinct legal authorities this system analyses against.

    ADR-003 and blueprint §2.1: suitability, fitness, PIV credentialing, and national-security
    eligibility are distinct authorities with distinct criteria. Collapsing them produces
    analysis that is wrong in a way that is hard to detect, so every finding names exactly one.
    """

    SUITABILITY = "suitability"
    FITNESS = "fitness"
    NATIONAL_SECURITY_ELIGIBILITY = "national_security_eligibility"
    PIV_CREDENTIALING = "piv_credentialing"


class Confidence(StrEnum):
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"


class ValidationOutcome(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    NOT_APPLICABLE = "not_applicable"
